### ISSUE TITLE
option_errcode_tの文字列化

### ISSUE THREAD

**Issue by yumetodo** [shosone/consoleapp#6]
```c
typedef enum{
    OPTION_SUCCESS             = 0,
    OPTION_OPT_NAME_IS_NULL    = 1,
    OPTION_OUT_OF_MEMORY       = 2,
    OPTION_MIN_BIGGER_THAN_MAX = 3,
    OPTION_OPT_PROP_DB_IS_NULL = 4,
    OPTION_DUPLICATE_SAME_OPT  = 5,
    OPTION_TOO_MANY_CONTENTS   = 6,
    OPTION_TOO_LITTLE_CONTENTS = 7,
}option_errcode_t;
```

に対してsampleでは

```c
    switch(ret){
        case OPTION_SUCCESS: /* success */
            break;

        case OPTION_OPT_NAME_IS_NULL:
            fprintf(stderr, "error: out of memory\n");
            exit(1);

        case OPTION_OUT_OF_MEMORY:
            fprintf(stderr, "error: flag_prop_db is null\n");
            exit(1);

        case OPTION_DUPLICATE_SAME_OPT:
            fprintf(stderr, "error: duplicate same flag\n");
            exit(1);

        case OPTION_TOO_MANY_CONTENTS:
            fprintf(stderr, "error: too many contents\n");
            exit(1);

        case OPTION_TOO_LITTLE_CONTENTS:
            fprintf(stderr, "error: too little contents\n");
            exit(1);

        default:
            fprintf(stderr, "there is a bug! (line: %d)\n", __LINE__);
            exit(100);
    }
```

のようなswitch文をかいているが、こういうのはライブラリ側で提供するべきではないか。つまり

```c
const char* option_errcode_t_format_message(option_errcode_t ec)
{
    static const char* messages[] = {
        "success",//OPTION_SUCCESS
        "out of memory",//OPTION_OPT_NAME_IS_NULL
        "flag_prop_db is null",//OPTION_OUT_OF_MEMORY
        "duplicate same flag",//OPTION_DUPLICATE_SAME_OPT
        "too many contents",//OPTION_TOO_MANY_CONTENTS
        "too little contents",//OPTION_TOO_LITTLE_CONTENTS
    };
    return (ec < 0 || 7 < ec) ? "unkown error code" : messages[ec];
}
```

のような関数を提供するべきではないか。。

**Comment by shosone** [comment]
なるほど！！
修正しておきます。

**Comment by shosone** [comment]
これからこのissuecloseに向けてがんばります。

**Comment by yumetodo** [comment]
すみません、それだと解決しないです。
https://cpprefjp.github.io/reference/system_error/error_category.html
のような`std::error_category`を継承したエラーカテゴリークラスを実装するときに、単に文字列を返却する関数がないと実装できないです。
ゆえに

```c
const char* option_errcode_t_format_message(option_errcode_t ec)
```

のようなインターフェースを提案していました。

そもそもエラーメッセージをどこに出すかはユーザーが決めることなので、`stderr`固定というのは・・・

**Comment by shosone** [comment]
なるほど、、、そういうのもあるんですね
c++にはいつか対応させたいと思ってたのでじゃあ今からそれに合わせておきます。

> そもそもエラーメッセージをどこに出すかはユーザーが決めることなので、`stderr`固定というのは・・・  

でも`stderr`以外に出力した方が良い場面ってあります？ あるとしてもかなりまれだと思うのでその場合はライブラリのユーザではなくライブラリを使用して作られたプログラムのユーザがリダイレクト等で対処すべきだと思うのですが。
自分は`option_property_t`の内容から明らかにエラーだと言えるものは`libconcoleapp.a`側で処理させて、明らかにエラーかわからないエラーは`contentsChecker`で処理させれば良いという考えです。

**Comment by shosone** [comment]
オプションの指定方法を間違った際のエラーメッセージをファイルに出力しないといけない場面って普通にあります？あったとしてもファイルに出力されるように固定されてたら困るくないですか？

https://cpprefjp.github.io/reference/system_error/error_category.html
の対応はするつもりなんですけどとりあえずcだけで動くものを一旦作ろうと思うのでこのissueは当分消せないかもしれません。。

**Comment by yumetodo** [comment]
価値観の問題なのでこれ以上はなんとも。自分は勝手に標準エラー出力やファイルになにか書かれるというのが恐怖なので。

**Comment by shosone** [comment]
エラーメッセージの出力を強制するエラーと強制しないエラーを分けました。
エラーメッセージの出力を強制するエラー
```c
typedef enum{
    OPTION_SHORT_FORM_IS_NULL,
    OPTION_MIN_BIGGER_THAN_MAX, 
    OPTION_PROP_GP_IS_NULL, 
    OPTION_SAME_PRIORITY,
    OPTION_SAME_SHORT_LONG_FORMAT,
    OPTION_PRIORITY_IS_OPTION_SUCCESS,
}option_api_usage_errcode_t;
```
エラーメッセージの出力を強制しないエラー
```c
typedef enum{
    OPTION_DUPLICATE_SAME_OPT,
    OPTION_TOO_MANY_CONTENTS, 
    OPTION_TOO_LITTLE_CONTENTS, 
}option_end_usr_errcode_t;
```
強制しないエラーではグローバル変数`option_errmsg`に文言が登録されます。
```c
const char* option_errcode_t_format_message(option_errcode_t ec)
```
のようなインタフェースにしてない理由は、エラーが発生したオプションによって文言が動的に変わるからです。
もし、ユーザが自身で考えたエラーメッセージを表示させたければグローバル変数`option_errno`の値をもとにメッセージ作ることができます。
c++は使い慣れていないのでよくわからないのですが
https://cpprefjp.github.io/reference/system_error/error_category.html
を使うことによるメリットででかいですか？

**Comment by yumetodo** [comment]
`std::logic_error`と`std::runtime_error`みたいな別れ方をしましたね・・・。
https://cpprefjp.github.io/reference/stdexcept.html

>エラーが発生したオプションによって文言が動的に変わるからです。

それでも関数として外部公開したほうがいいと思います。グローバル変数は公開するものではないので・・・。

**Comment by shosone** [comment]
おお、本当ですね。でもやっぱりそうなりますよね。

>それでも関数として外部公開したほうがいいと思います。グローバル変数は公開するものではないので・・・。  

アドバイスありがとうございます。どっちにしようか迷ってたので後々そうしようと思います。

**Comment by shosone** [comment]
修正完了です！
これで公開される情報は`option_errno`と`optionErrno2msg()`のみになりました。  
`option_errno`で発生したエラーを把握し、  
`optionErrno2mdg(option_errno)`でエラーメッセージを取得することができます。
ちなみに実際に使っているようすはoption_sample.cで確認できます。

**Comment by yumetodo** [comment]
`errno`という変数名は`errno.h`のそれと衝突しそう・・・

**Comment by shosone** [comment]
むむ、どういうことです？`errno`じゃなくて`option_errno`だから衝突しないと思いますが
ローカル変数としての`errno`は使ってますけど、、、

**Comment by yumetodo** [comment]
やっぱり衝突した。

```
/home/yumetodo/Documents/consoleapp/sample/c/sample_option.c: In function ‘main’:
/home/yumetodo/Documents/consoleapp/sample/c/sample_option.c:45:63: warning: passing argument 1 of ‘optionErrno2msg’ makes pointer from integer without a cast [-Wint-conversion]
         fprintf(stderr, "option error: %s\n", optionErrno2msg(option_errno));
                                                               ^~~~~~~~~~~~
In file included from /home/yumetodo/Documents/consoleapp/sample/c/../../src/option.h:34:0,
                 from /home/yumetodo/Documents/consoleapp/sample/c/sample_option.c:7:
/home/yumetodo/Documents/consoleapp/sample/c/../../src/./option_errmsg.h:54:1: note: expected ‘option_runtime_errno_t * (*)() {aka enum <anonymous> * (*)()}’ but argument is of type ‘int’
 optionErrno2msg(
 ^~~~~~~~~~~~~~~
```

**Comment by yumetodo** [comment]
option_sample.cのなるべく先頭でerrno.hをincludeしてみてください。

**Comment by shosone** [comment]
*/use/include/*以下のheaderを見ると関数の引数にprefix __ を付けているファイルが多かったので真似しました。
ちなみに2つあるのはANSIではアンダースコア1つで始まる名前は処理系が独自の目的で使用する可能性があるからだそうです。
http://akademeia.info/index.php?C%B8%C0%B8%EC%2F%CA%B8%CB%A1%2F%A5%D8%A5%C3%A5%C0%A5%D5%A5%A1%A5%A4%A5%EB

**Comment by yumetodo** [comment]
だめです

>C++11: Syntax and Feature
>http://ezoeryou.github.io/cpp-book/C++11-Syntax-and-Feature.xhtml#lex.name
>以下のいずれかの条件に当てはまる名前は、あらゆる利用を予約されている。
>ひとつのアンダースコアに大文字から始まる名前
 >アンダースコアが二つ連続している、いわゆるダブルアンダースコアを含む名前

**Comment by shosone** [comment]
まじですか。了解です。
