### ISSUE TITLE
linuxでsampleが動かなくなる原因を調査中です

### ISSUE THREAD

**Issue by shosone** [shosone/consoleapp#7]
まだ本腰入れて調査してないですがとりあえずどのコミットから動かなくなるのか調べたのでlinux_stableというタグを付けてpushしました。クロスプラットフォーム化の勉強になるのでこの件は当方におまかせください（＿）ｂ
ちなみに最新バージョンでWinでは動きますか？

**Comment by yumetodo** [comment]
再現手順がほしいです。`sample.exe`を引数無しで呼び出すだけではセグフォリません。

**Comment by shosone** [comment]
直りました！
どこがどう悪かったのかは特定できなかったですが、option.cのメモリ確保周りにバグがあったみたいです。
得にdecodeOptions()周りはかなりややこしいことしちゃっているのでそこが怪しいですね。

@yumetodo さんの修正で反映したのは
- 変数名の変更 （ポインタと明示したい変数に_pサフィックスをつける）
- strcpyではなくmemcpyを使う
- 同じ処理結果を一時変数で流用
などです。
採用しなかったのは、
- メモリ確保前にSIZE_MAXを超えていないか調べる処理は超えていたらmallocなどでfreeが返るので削除
- NULLチェックで私は == NULL と書く派なので変えさせていただきました。実験的にisNullマクロを使ってみようと思います。（また勝手に返るかもしれません。ちなみに私は何かところころ変えちゃいます。）
などです。

**Comment by shosone** [comment]
ちなみに再現手順は
./sample/sample hoge
でhogeの部分に何を入れてもセグフォってました。
