### ISSUE TITLE
reallocarrayを使わない

### ISSUE THREAD

**Issue by yumetodo** [shosone/consoleapp#8]
reallocarrayはC標準にない。

**Comment by yumetodo** [comment]
https://github.com/shosone/consoleapp/issues/7#issuecomment-429756990
>     * メモリ確保前にSIZE_MAXを超えていないか調べる処理は超えていたらmallocなどでfreeが返るので削除

これは

```c
(0 < new_argc && (size_t)new_argc < (SIZE_MAX / sizeof(char *)))
```

のような処理のことを指していると思うが、これは`reallocarray`から`realloc`に書き換えた際に`reallocarray`の内部処理相当(`new_argc * sizeof(char*)`がoverflowしないかの確認)を追加したもので必要なもの。さもなくば意図しない小さなメモリーサイズになり、buffer overrunするであろう。

**Comment by shosone** [comment]
なるほどそういうことでしたか。
気づかなくてすいません。修正しておきます。

**Comment by shosone** [comment]
一応確認したいんですけど
@yumetodo さんがコミットしてくれたコードが下のようになっているんですが
```c
            if(
                    (0 < new_argc && (size_t)new_argc < (SIZE_MAX / sizeof(char *)))
                    || NULL == ((*new_argv_p) = (char **)realloc(*new_argv_p, new_argc * sizeof(char *)))
              ){
                ret = OUT_OF_MEMORY;
                goto free_and_exit;
            }
```
このif分の条件式`0 < new_argc && (size_t)new_argc < (SIZE_MAX / sizeof(char *)))`は`!(0 < new_argc && (size_t)new_argc < (SIZE_MAX / sizeof(char *))))`の間違いですか？

**Comment by yumetodo** [comment]
> このif分の条件式0 < new_argc && (size_t)new_argc < (SIZE_MAX / sizeof(char *)))は!(0 < new_argc && (size_t)new_argc < (SIZE_MAX / sizeof(char *))))の間違いですか？

あっ、やらかしてた。ご指摘のとおりです。
